
const channel = [
  { code: "002", name: "Bank Rakyat Indonesia (BRI)", status: "Active" },
  { code: "003", name: "Bank Ekspor Indonesia", status: "Active" },
  { code: "008", name: "Bank Mandiri", status: "Active" },
  { code: "009", name: "BNI (Bank Negara Indonesia)", status: "Active" },
  { code: "011", name: "Bank Danamon", status: "Active" },
  { code: "013", name: "Permata", status: "Active" },
  { code: "014", name: "Bank Central Asia (BCA)", status: "Active" },
  { code: "016", name: "Maybank Indonesia", status: "Active" },
  { code: "022", name: "CIMB Niaga", status: "Active" },
  { code: "028", name: "Bank OCBC NISP", status: "Active" },
  { code: "031", name: "Citibank", status: "Active" },
  { code: "041", name: "HSBC Indonesia", status: "Active" },
  { code: "046", name: "DBS Indonesia", status: "Active" },
  { code: "050", name: "Standard Chartered Bank", status: "Active" },
  { code: "110", name: "BJB", status: "Active" },
  { code: "111", name: "Bank DKI", status: "Active" },
  { code: "112", name: "Bank BPD DIY", status: "Active" },
  { code: "114", name: "Bank Jatim", status: "Active" },
  { code: "117", name: "Bank Sumut", status: "Active" },
  { code: "120", name: "Bank Sumsel Babel", status: "Active" },
  { code: "122", name: "Bank Kalsel", status: "Active" },
  { code: "126", name: "Bank Sulselbar", status: "Active" },
  { code: "129", name: "BPD Bali", status: "Active" },
  { code: "133", name: "Bank Bengkulu", status: "Active" },
  { code: "137", name: "BPD Banten", status: "Active" },
  { code: "145", name: "Bank Nusantara Parahyangan", status: "Active" },
  { code: "147", name: "Muamalat", status: "Active" },
  { code: "151", name: "Bank Mestika Dharma", status: "Active" },
  { code: "153", name: "Bank Sinarmas", status: "Active" },
  { code: "161", name: "Bank Ganesha", status: "Active" },
  { code: "164", name: "ICBC Indonesia", status: "Active" },
  { code: "167", name: "QNB Indonesia", status: "Active" },
  { code: "200", name: "BTN", status: "Active" },
  { code: "213", name: "BTPN", status: "Active" },
  { code: "426", name: "Bank Mega", status: "Active" },
  { code: "441", name: "Bank Bukopin", status: "Active" },
  { code: "451", name: "BSI (Bank Syariah Indonesia)", status: "Active" },
  { code: "472", name: "Bank Jasa Jakarta", status: "Active" },
  { code: "484", name: "LINE Bank", status: "Active" },
  { code: "490", name: "Neo Commerce", status: "Active" },
  { code: "501", name: "Blu", status: "Active" },
  { code: "503", name: "Nobu Bank", status: "Active" },
  { code: "513", name: "Bank Ina Perdana", status: "Active" },
  { code: "523", name: "Bank Sahabat Sampoerna", status: "Active" },
  { code: "531", name: "Bank Amar Indonesia", status: "Active" },
  { code: "535", name: "Seabank", status: "Active" },
  { code: "542", name: "Bank Jago", status: "Active" },
  { code: "553", name: "Bank Mayora Indonesia", status: "Active" },
  { code: "567", name: "Allo Bank", status: "Active" },
  { code: "950", name: "Commonwealth Bank", status: "Active" },
  { code: "ovo", name: "OVO", status: "Active" },
  { code: "dana", name: "Dana", status: "Active" },
  { code: "gopay", name: "GoPay", status: "Active" },
  { code: "linkaja", name: "LinkAja", status: "Active" }
];

export default channel;